version: '3.8'

services:
  budget-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  budget-service-dev:
    image: ghcr.io/userver-framework/ubuntu-24.04-userver:latest
    privileged: true
    network_mode: bridge
    environment:
      - CCACHE_DIR=/app/.ccache
    volumes:
      - .:/app:rw
    ports:
      - "8080:8080"
    working_dir: /app
    entrypoint:
      - ./run_as_user.sh
    profiles:
      - dev
